---
- hosts: all
  gather_facts: True
  tasks:
    - name: upgrade to the latest state
      apt:
        upgrade: dist
        autoremove: yes
        state: present
        update_cache: yes
  become: yes
