---
- name: generate random encryption key
  shell: head -c 32 /dev/urandom | base64
  register: encryption_key

- name: configure the encryption
  template:
    src: encryption-config.yaml.j2
    dest: "{{ ansible_user_dir }}/encryption-config.yaml"
  when: inventory_hostname in groups['masters']
  
